### ISSUE TITLE
Allow migrating the database

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/ansible-role-rsd#104]
With every release of the RSD, a migration script will be provided here:

https://github.com/research-software-directory/RSD-production/tree/main/database-migration/migration-scripts

It would be handy if we could run those automatically when deploying a new version. Please note that the versions specified in the file names refer to the RSD version, and not the version of the database image!

**Comment by Normo** [comment]
Thanks @cmeessen. 

This is will not be easy to implement the logic behind this update process I guess. Currently we use `rsd_version` to specify the used container image tag, which can be the RSD version like `v1.10.0`, `hifis-1.2.1` or even a commit hash e.g. `e024a5584c4f3bc7b4f30059fe269819372076c0`. So we have to distinguish between the actual RSD version and the container images tag. In addition we have to add the migration scripts to this repo and keep track of them.

In fact, I actually see this should more likely to be be implemented in the rsd-as-a-service upstream project. What do you think @cmeessen @tobiashuste ?
